name: .NET Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 3.0.x

      - name: Verify fomatting
        run: dotnet format '.' --verify-no-changes

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build ./Backtrace/Backtrace.csproj --no-restore --configuration Release

      - name: Run tests
        run: dotnet test Backtrace.Tests --verbosity normal

  test_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build ./Backtrace/Backtrace.csproj --no-restore --configuration Release

      - name: Run tests
        run: dotnet test Backtrace.Tests --verbosity normal
