name: Publish NuGet Package

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Extract version from tag
        run: echo VERSION=${GITHUB_REF#refs/tags/v} >> $env:GITHUB_ENV

      - name: version
        run: echo "./output/Backtrace$PACKAGE_VERSION.nupkg"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ./Backtrace/Backtrace.csproj --no-restore --configuration Release

      - name: Pack
        run: dotnet pack ./Backtrace/Backtrace.csproj --configuration Release --no-build -o ./output/

      - name: print current tag version
        run: echo $GITHUB_REF ./output/Backtrace$GITHUB_REF.nupkg

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./output/Backtrace$PACKAGE_VERSION.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
